# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_spec',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_format', models.CharField(max_length=10)),
                ('data_modificator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('serial', models.IntegerField(primary_key=True, serialize=False)),
                ('device_password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Devices')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('login', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Users'),
        ),
        migrations.AddField(
            model_name='devices',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Device_spec'),
        ),
    ]
