# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indication',
            name='id',
        ),
        migrations.AlterField(
            model_name='indication',
            name='arrival_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indication',
            name='serial',
            field=models.IntegerField(),
        ),
    ]
