# Generated by Django 2.0 on 2018-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0003_auto_20180307_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='indication',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='indication_stream',
            name='indication',
            field=models.CharField(default='', max_length=30),
        ),
    ]
